server:
  port: 8080

project:
  version: @projectVersion@

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

spring:
  application:
    name: metrology-app
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/metrology
    username: postgres
    password: postgres

  jpa:
#    hibernate:
#      ddl-auto: create-drop
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml